import type { Icon } from "@/lib/kicon";
import {
  ArrowsClockwise,
  ArrowsLeftRight,
  Bank,
  BookOpenText,
  Briefcase,
  Coins,
  CurrencyBtc,
  Flag,
  GasPump,
  Gift,
  Globe,
  Graph,
  Hexagon,
  Image,
  Key,
  Lightning,
  Link,
  Lock,
  MagnifyingGlass,
  MapPin,
  Shield,
  ShoppingBag,
  Siren,
  Stack,
  UserMinus,
  UsersThree,
  Wallet,
} from "@/lib/kicon";
import type { LessonIcon } from "@/lib/curriculum";

export type AppIcon = Icon;

export const LESSON_ICONS: Record<LessonIcon, Icon> = {
  globe: Globe,
  layers: Stack,
  link: Link,
  bank: Bank,
  wallet: Wallet,
  key: Key,
  lock: Lock,
  map: MapPin,
  bitcoin: CurrencyBtc,
  hexagon: Hexagon,
  coins: Coins,
  image: Image,
  badge: ShoppingBag,
  swap: ArrowsLeftRight,
  fuel: GasPump,
  network: Graph,
  shield: Shield,
  siren: Siren,
  userx: UserMinus,
  gift: Gift,
  flag: Flag,
  book: BookOpenText,
  briefcase: Briefcase,
  users: UsersThree,
  zap: Lightning,
  search: MagnifyingGlass,
  repeat: ArrowsClockwise,
};
