export type ProofTone = "up" | "down" | "warn" | "info" | "drop";

export type Proof = {
  id: string;
  src: string;
  tone: ProofTone;
  value: string;
  cap: string;
  via: string;
};

export const TONE_UI: Record<ProofTone, { label: string; border: string; text: string }> = {
  up: { label: "Cuan", border: "border-unit-teal", text: "text-unit-teal" },
  down: { label: "Hangus", border: "border-danger", text: "text-danger" },
  warn: { label: "Waspada", border: "border-streak", text: "text-streak" },
  info: { label: "Fakta", border: "border-candy-300", text: "text-candy-600" },
  drop: { label: "Airdrop", border: "border-unit-purple", text: "text-unit-purple" },
};

export const PROOFS: Proof[] = [
  {
    id: "cuan-20m",
    src: "/proof/cuan-20m.jpg",
    tone: "up",
    value: "Rp 20 M",
    cap: "4 bulan memecoin",
    via: "X · @vespamatic96",
  },
  {
    id: "cuan-argus",
    src: "/proof/cuan-argus.jpg",
    tone: "up",
    value: "Rp 17,69 M",
    cap: "Rp 8,8 jt → 2.000x $ARGUS",
    via: "X · @vespamatic96",
  },
  {
    id: "cuan-argus2",
    src: "/proof/cuan-argus2.jpg",
    tone: "up",
    value: "2,6% supply",
    cap: "masih pegang, sebagian sudah dijual",
    via: "X · @vespamatic96",
  },
  {
    id: "cuan-421k",
    src: "/proof/cuan-421k.jpg",
    tone: "up",
    value: "+$421 rb",
    cap: "profit $MEME",
    via: "X · @pnlsdaily",
  },
  {
    id: "cuan-300k",
    src: "/proof/cuan-300k.jpg",
    tone: "up",
    value: "+$300 rb",
    cap: "realized, bukan kertas",
    via: "X · @0xsamarai",
  },
  {
    id: "cuan-1m-week",
    src: "/proof/cuan-1m-week.jpg",
    tone: "up",
    value: "+$1,09 jt",
    cap: "7 hari, 22 orang",
    via: "X · @CryptoTalkMan",
  },
  {
    id: "cuan-knots",
    src: "/proof/cuan-knots.jpg",
    tone: "up",
    value: "$31 rb → $850 rb",
    cap: "27x, nambah di dip",
    via: "X · @CryptoWithJack",
  },
  {
    id: "cuan-pnut17",
    src: "/proof/cuan-pnut17.jpg",
    tone: "up",
    value: "$3 jt dari $17",
    cap: "$PNUT, lalu berhenti",
    via: "X · @10genn",
  },
  {
    id: "cuan-winter",
    src: "/proof/cuan-winter.jpg",
    tone: "up",
    value: "+$179,89 jt",
    cap: "lifetime MM, bukan HP",
    via: "X · @OnchainLens",
  },
  {
    id: "cuan-whale",
    src: "/proof/cuan-whale.jpg",
    tone: "up",
    value: "+$6,6 jt",
    cap: "PnL paus, satu long",
    via: "X · @DustyBC",
  },
  {
    id: "cuan-zec-120k",
    src: "/proof/cuan-zec-120k.jpg",
    tone: "up",
    value: "+$120 rb",
    cap: "long $ZEC ditutup",
    via: "X · @Crypto__Haris",
  },
  {
    id: "cuan-hl",
    src: "/proof/cuan-hl.jpg",
    tone: "up",
    value: "Top 900",
    cap: "Hyperliquid, dari HP",
    via: "X · @0xbobateas",
  },
  {
    id: "cuan-indo-lev",
    src: "/proof/cuan-indo-lev.jpg",
    tone: "up",
    value: "+$1.300",
    cap: "1 bulan, utang $630",
    via: "X · @Cherubiuma",
  },
  {
    id: "cuan-binance",
    src: "/proof/cuan-binance.jpg",
    tone: "up",
    value: "Top 7 hari",
    cap: "leaderboard Binance",
    via: "X · @CryptomechanicX",
  },
  {
    id: "rugi-33m",
    src: "/proof/rugi-33m.png",
    tone: "down",
    value: "−$33,66 jt",
    cap: "satu posisi short",
    via: "X · @coinbureau",
  },
  {
    id: "rugi-30m",
    src: "/proof/rugi-30m.jpg",
    tone: "down",
    value: "−$30 jt",
    cap: "PnL 30 hari",
    via: "X · @OnchainLens",
  },
  {
    id: "rugi-machi",
    src: "/proof/rugi-machi.jpg",
    tone: "down",
    value: "−$5,1 jt",
    cap: "seminggu, lalu potong",
    via: "X · @lookonchain",
  },
  {
    id: "rugi-liqs",
    src: "/proof/rugi-liqs.jpg",
    tone: "down",
    value: "$1 jt hangus",
    cap: "flip long→short, likuidasi",
    via: "X · @lookonchain",
  },
  {
    id: "rugi-sp500",
    src: "/proof/rugi-sp500.jpg",
    tone: "down",
    value: "$7,19 jt",
    cap: "short SP500 dilikuidasi",
    via: "X · @lookonchain",
  },
  {
    id: "rugi-roundtrip",
    src: "/proof/rugi-roundtrip.png",
    tone: "down",
    value: "Jutaan → 0",
    cap: "full port, roundtrip",
    via: "X · @itswhail",
  },
  {
    id: "rugi-cut",
    src: "/proof/rugi-cut.jpg",
    tone: "down",
    value: "−$100 rb",
    cap: "dipotong, bukan diharap",
    via: "X · @ljcryptotrades",
  },
  {
    id: "rugi-cut2",
    src: "/proof/rugi-cut2.jpg",
    tone: "down",
    value: "Merah juga dipost",
    cap: "yang hidup nunjukin luka",
    via: "X · @ljcryptotrades",
  },
  {
    id: "rugi-personal",
    src: "/proof/rugi-personal.jpg",
    tone: "down",
    value: "−$426",
    cap: "satu hari, greed",
    via: "X · @Crypto_Zh0u",
  },
  {
    id: "rugi-entry",
    src: "/proof/rugi-entry.jpg",
    tone: "down",
    value: "−$1.200",
    cap: "harga naik, dia tetap minus",
    via: "X · @karbonbased",
  },
  {
    id: "rugi-nuked",
    src: "/proof/rugi-nuked.jpg",
    tone: "down",
    value: "−90% / jam",
    cap: "bukan rug, tetap bolong",
    via: "X · @JJcycles",
  },
  {
    id: "rugi-paper",
    src: "/proof/rugi-paper.jpg",
    tone: "down",
    value: "Masih kertas",
    cap: "hijau di layar, belum keluar",
    via: "X · @stackzz",
  },
  {
    id: "rugi-float",
    src: "/proof/rugi-float.jpg",
    tone: "down",
    value: "0 yang $1 jt",
    cap: "24 jam, top trader FOMO",
    via: "X · @duta_crypto",
  },
  {
    id: "fumble-193m",
    src: "/proof/fumble-193m.jpg",
    tone: "down",
    value: "$286 vs $193 jt",
    cap: "jual 2 menit, ATH kemudian",
    via: "X · @voided",
  },
  {
    id: "scam-drainer",
    src: "/proof/scam-drainer.jpg",
    tone: "warn",
    value: "Kit $210",
    cap: "drainer 610+ wallet dijual",
    via: "X · @DarkWebInformer",
  },
  {
    id: "warn-seed",
    src: "/proof/warn-seed.jpg",
    tone: "warn",
    value: "12 kata",
    cap: "bukan chart — ini layar paling rawan",
    via: "X · @gregwrites_yy",
  },
  {
    id: "warn-seed-rules",
    src: "/proof/warn-seed-rules.jpg",
    tone: "warn",
    value: "Jangan screenshot",
    cap: "tulis kertas / plat, offline",
    via: "X · @Josephb3112",
  },
  {
    id: "warn-sparkkitty",
    src: "/proof/warn-sparkkitty.jpg",
    tone: "warn",
    value: "Malware galeri",
    cap: "app palsu scan foto seed",
    via: "X · @Jessdotfun",
  },
  {
    id: "warn-sparkkitty2",
    src: "/proof/warn-sparkkitty2.png",
    tone: "warn",
    value: "OCR 12/24 kata",
    cap: "hapus foto seed, cek izin galeri",
    via: "X · @0xcut_",
  },
  {
    id: "warn-hw",
    src: "/proof/warn-hw.jpg",
    tone: "info",
    value: "Seed = master key",
    cap: "perangkat cuma pelindung, seed-nya raja",
    via: "X · @DCENTWALLETS",
  },
  {
    id: "warn-honeypot",
    src: "/proof/warn-honeypot.jpg",
    tone: "warn",
    value: "+605% kertas",
    cap: "semua hijau, nggak ada yang bisa jual",
    via: "X · @gandalfcryptto",
  },
  {
    id: "warn-honeypot2",
    src: "/proof/warn-honeypot2.jpg",
    tone: "warn",
    value: "$10 → $200",
    cap: "30 menit, lalu tombol jual mati",
    via: "X · @CloverJat",
  },
  {
    id: "warn-honeypot3",
    src: "/proof/warn-honeypot3.jpg",
    tone: "warn",
    value: "+400% macet",
    cap: "beli bisa, jual nggak",
    via: "X · @Lina_CryptoA",
  },
  {
    id: "warn-honeypot4",
    src: "/proof/warn-honeypot4.jpg",
    tone: "warn",
    value: "+$6, rug",
    cap: "token udah rug, sisanya nggak bisa dijual",
    via: "X · @JuneCribb",
  },
  {
    id: "warn-never-dm",
    src: "/proof/warn-never-dm.jpg",
    tone: "warn",
    value: "CS nggak DM dulu",
    cap: "seed / password / remote = scam",
    via: "X · @uex_us",
  },
  {
    id: "warn-official",
    src: "/proof/warn-official.jpg",
    tone: "warn",
    value: "Cek domain",
    cap: "admin nggak minta seed, nggak DM dulu",
    via: "X · @akadotfun",
  },
  {
    id: "warn-phishing",
    src: "/proof/warn-phishing.jpg",
    tone: "warn",
    value: "Shutdown = umpan",
    cap: "bursa tutup, phishing meledak",
    via: "X · @_CryptoYoda",
  },
  {
    id: "warn-redpill",
    src: "/proof/warn-redpill.jpg",
    tone: "warn",
    value: "Simulasi bohong",
    cap: "preview aman, tx asli nguras",
    via: "X · @Crypto__Goku",
  },
  {
    id: "warn-rug",
    src: "/proof/warn-rug.jpg",
    tone: "warn",
    value: "Rug pull",
    cap: "tim cabut, likuiditas hilang",
    via: "X · @fluxzone001",
  },
  {
    id: "warn-airdrop-honey",
    src: "/proof/warn-airdrop-honey.jpg",
    tone: "warn",
    value: "Airdrop honeypot",
    cap: "dikirim gratis, nggak bisa dijual",
    via: "X · @MINHxDYNASTY",
  },
  {
    id: "warn-revoke",
    src: "/proof/warn-revoke.jpg",
    tone: "info",
    value: "revoke.cash",
    cap: "cabut izin setelah situs random",
    via: "X · @bashorunedward",
  },
  {
    id: "warn-revoke-id",
    src: "/proof/warn-revoke-id.jpg",
    tone: "info",
    value: "Cek kesehatan wallet",
    cap: "rutin revoke setelah degen",
    via: "X · @azwardiiqbal",
  },
  {
    id: "warn-drained",
    src: "/proof/warn-drained.jpg",
    tone: "down",
    value: "Wallet dikuras",
    cap: "klik partnership palsu di timeline",
    via: "X · @zkxwallet",
  },
  {
    id: "warn-zach",
    src: "/proof/warn-zach.jpg",
    tone: "warn",
    value: "$1,2 jt hangus",
    cap: "email Trezor palsu, seed ketik",
    via: "X · @zachxbt",
  },
  {
    id: "warn-urgent",
    src: "/proof/warn-urgent.jpg",
    tone: "warn",
    value: "Klik sekarang",
    cap: "urgensi palsu = pola phishing",
    via: "X · @uex_us",
  },
  {
    id: "warn-approval",
    src: "/proof/warn-approval.jpg",
    tone: "warn",
    value: "$58 jt",
    cap: "Radiant: izin terbuka disedot",
    via: "X · @zachxbt",
  },
  {
    id: "warn-scam-arc",
    src: "/proof/warn-scam-arc.jpg",
    tone: "down",
    value: "−$35 token scam",
    cap: "2 hari dihajar token sampah",
    via: "X · @duta_crypto",
  },
  {
    id: "info-airdrop-sold",
    src: "/proof/info-airdrop-sold.jpg",
    tone: "info",
    value: "Airdrop dijual total",
    cap: "hadiah ≠ wajib hold",
    via: "X · @cryptondo",
  },
  {
    id: "drop-uni",
    src: "/proof/drop-uni.jpg",
    tone: "drop",
    value: "400 UNI",
    cap: "swap kecil, token nyangkut. Modal gas.",
    via: "Uniswap 2020",
  },
  {
    id: "drop-uni-pair",
    src: "/proof/drop-uni-pair.jpg",
    tone: "drop",
    value: "Klaim 400 UNI",
    cap: "pake DEX, bukan all-in chart",
    via: "Uniswap claim",
  },
  {
    id: "drop-arb",
    src: "/proof/drop-arb.jpg",
    tone: "drop",
    value: "1.750 ARB",
    cap: "pake L2. Eligible. Bukan transfer dulu.",
    via: "Arbitrum Foundation",
  },
  {
    id: "drop-arb-claim",
    src: "/proof/drop-arb-claim.jpg",
    tone: "drop",
    value: "Claim ARB",
    cap: "situs yang kamu ketik sendiri",
    via: "Arbitrum Foundation",
  },
  {
    id: "drop-hype-dist",
    src: "/proof/drop-hype-dist.jpg",
    tone: "drop",
    value: "Rata-rata 2.881 HYPE",
    cap: "94 ribu orang. Bukan trading PnL.",
    via: "ASXN · CoinGecko",
  },
  {
    id: "drop-hype-avg",
    src: "/proof/drop-hype-avg.jpg",
    tone: "drop",
    value: "±$30 rb / akun",
    cap: "headline airdrop Hyperliquid",
    via: "Odaily",
  },
  {
    id: "drop-hype-price",
    src: "/proof/drop-hype-price.jpg",
    tone: "drop",
    value: "$3,90 di hari klaim",
    cap: "HYPE TGE. Yang pegang, naik belakangan.",
    via: "CoinGecko",
  },
  {
    id: "drop-jup",
    src: "/proof/drop-jup.jpg",
    tone: "drop",
    value: "Klaim $JUP",
    cap: "pake aggregator Solana, bukan kirim dulu",
    via: "Jupiter",
  },
  {
    id: "drop-uni-400",
    src: "/proof/drop-uni-400.jpg",
    tone: "drop",
    value: "400 UNI",
    cap: "beberapa swap. Modal gas. 6 tahun lalu.",
    via: "X · @airdropblogs",
  },
  {
    id: "drop-uni-ath",
    src: "/proof/drop-uni-ath.jpg",
    tone: "drop",
    value: "400 UNI → ~$18 rb",
    cap: "di puncak 2021. Satu-dua swap.",
    via: "X · @Vanquan_titans",
  },
  {
    id: "drop-uni-gaji",
    src: "/proof/drop-uni-gaji.jpg",
    tone: "drop",
    value: "$4 rb–$6 rb",
    cap: "Uniswap, beberapa perintah swap. Bukan futures.",
    via: "X · @TMxCrypto",
  },
  {
    id: "drop-arb-1500",
    src: "/proof/drop-arb-1500.jpg",
    tone: "drop",
    value: "1.500 ARB",
    cap: "airdrop pertama. Wallet ICU, tetap cair.",
    via: "X · @onchainmonk",
  },
  {
    id: "drop-arb-8k",
    src: "/proof/drop-arb-8k.jpg",
    tone: "drop",
    value: "$8.000 ARB",
    cap: "pake L2. Lalu modal buat farm berikutnya.",
    via: "X · @Coco_Airdrop",
  },
  {
    id: "drop-jup-300",
    src: "/proof/drop-jup-300.jpg",
    tone: "drop",
    value: "$300 tes JUP",
    cap: "sebelum airdrop utama. Pake aggregator.",
    via: "X · @0x_abu",
  },
  {
    id: "drop-jup-saved",
    src: "/proof/drop-jup-saved.jpg",
    tone: "drop",
    value: "JUP 2024",
    cap: "airdrop yang nolong. Bukan sinyal chart.",
    via: "X · @DokuroSOL",
  },
  {
    id: "drop-hype-18",
    src: "/proof/drop-hype-18.jpg",
    tone: "drop",
    value: "18,57 HYPE",
    cap: "nyangkut. Bukan PnL trading.",
    via: "X · @Satsyxbt",
  },
  {
    id: "drop-first-2k",
    src: "/proof/drop-first-2k.jpg",
    tone: "drop",
    value: "$2.000 pertama",
    cap: "tanpa beli. Airdrop. Waktu, bukan all-in.",
    via: "X · @IRasyuqa",
  },
  {
    id: "drop-arb-18k",
    src: "/proof/drop-arb-18k.png",
    tone: "drop",
    value: "2.125 ARB",
    cap: "$18 rb di wallet. Modal pake L2, bukan chart.",
    via: "X · @danhtran68",
  },
  {
    id: "drop-met-34k",
    src: "/proof/drop-met-34k.jpg",
    tone: "drop",
    value: "+$34 rb",
    cap: "Airdrop MET dicairin. Bukan PnL futures.",
    via: "X · @jussy_world",
  },
  {
    id: "drop-wif-1k5",
    src: "/proof/drop-wif-1k5.jpg",
    tone: "drop",
    value: "1.000 WIF",
    cap: "Nyangkut $1.500. Modal nol. Bukan trade.",
    via: "X · @notEezzy",
  },
  {
    id: "drop-dydx-32k",
    src: "/proof/drop-dydx-32k.jpg",
    tone: "drop",
    value: "1.163 DYDX",
    cap: "ATH $32 rb. Pake produk, token nyangkut.",
    via: "X · @Crypto4bailout",
  },
  {
    id: "drop-hl-tab",
    src: "/proof/drop-hl-tab.jpg",
    tone: "drop",
    value: "$356 airdrop",
    cap: "Tab Airdrop. Puncaknya ~$6.000. Modal pake.",
    via: "X · @kumafade",
  },
  {
    id: "drop-hl-pts",
    src: "/proof/drop-hl-pts.jpg",
    tone: "drop",
    value: "10.247 poin",
    cap: "Di-claim. Jadi 54.821 HYPE. Dijual terlalu cepat.",
    via: "X · @NOJOBNOPLANER",
  },
  {
    id: "drop-top50",
    src: "/proof/drop-top50.jpg",
    tone: "info",
    value: "Top 50 ATH",
    cap: "UNI, ARB, JUP, HYPE, ENS. Hadiah, syarat, dan risiko — bukan chart.",
    via: "CryptoRank",
  },
  {
    id: "warn-hl-phish",
    src: "/proof/warn-hl-phish.jpg",
    tone: "warn",
    value: "claim-hyperliquid.xyz",
    cap: "domain palsu. 1 huruf beda = umpan",
    via: "PCRisk",
  },
  {
    id: "warn-coinex",
    src: "/proof/warn-coinex.jpg",
    tone: "down",
    value: "$54,7 jt",
    cap: "CoinEx. 147 rb alamat, 70% dicuri dalam 3 hari. CEX bukan brankas.",
    via: "X · on-chain report",
  },
  {
    id: "warn-dict",
    src: "/proof/warn-dict.jpg",
    tone: "warn",
    value: "$3,5 jt",
    cap: "1.444 wallet. Seed kena brute-force kamus. 12 kata bukan mainan.",
    via: "X · on-chain report",
  },
  {
    id: "warn-seed-vuln",
    src: "/proof/warn-seed-vuln.jpg",
    tone: "warn",
    value: "1.444 korban",
    cap: "Seed di komputer / generator lemah. Offline, baja, jangan foto.",
    via: "X · on-chain report",
  },
  {
    id: "warn-tiffany",
    src: "/proof/warn-tiffany.jpg",
    tone: "warn",
    value: "DM palsu",
    cap: "Tiffany Fong: 'kalau DM minta connect wallet, itu bukan aku. Nggak ada NFT-ku.'",
    via: "X · @tiffanyfong_",
  },
];

export const QUIZ_CLIPS: Record<string, string[]> = {
  u1l1t3: ["drop-arb-18k", "drop-wif-1k5", "drop-met-34k", "drop-uni-ath"],
  u1l1q6: ["drop-arb-18k"],
  u1l1q7: ["drop-wif-1k5", "drop-first-2k"],
  u2l2t: ["warn-seed", "warn-seed-rules", "warn-dict", "warn-seed-vuln"],
  u2l5t: ["warn-hw", "warn-seed-vuln"],
  u2l5q3: ["warn-hw"],
  u2l6t: ["warn-scam-arc"],
  u2l6q1: ["warn-scam-arc"],
  u4l5t: ["warn-approval"],
  u4l5q3: ["warn-approval"],
  u5l11t: ["rugi-paper"],
  u6l5t: ["scam-drainer", "warn-drained"],
  u6l5q1: ["scam-drainer"],
  u6l5q3: ["warn-revoke"],
  u6l6t: ["warn-tiffany", "warn-zach"],
  u6l6q1: ["warn-zach"],
  u6l6q3: ["warn-tiffany"],
  u8l5t: ["rugi-liqs", "rugi-33m"],
  u8l5q3: ["rugi-liqs"],
  u10l5t: ["warn-redpill"],
  u10l5q3: ["warn-redpill"],
  u11l1t: ["warn-coinex"],
  u11l5t: ["warn-coinex"],
  u11l5q3: ["warn-coinex"],
  u12l5t: ["rugi-nuked"],
  u18l5t: ["warn-revoke", "warn-approval"],
  u18l5q1: ["warn-revoke"],
  u20l7t: ["warn-redpill"],
  u2l2q1: ["warn-seed"],
  u2l2q2: ["warn-never-dm"],
  u2l2q3: ["warn-sparkkitty"],
  u2l2q4: ["warn-hw"],
  u2l2q5: ["warn-seed-rules"],
  u2l3q2: ["warn-seed"],
  u2cp1: ["warn-seed"],
  u2cp2: ["warn-never-dm"],
  u2cp6: ["warn-seed-rules"],

  u6l1t: ["warn-phishing", "warn-official"],
  u6l1q1: ["warn-phishing"],
  u6l1q2: ["warn-official"],
  u6l1q3: ["warn-redpill"],
  u6l1q5: ["warn-never-dm"],
  u6l2t: ["warn-seed-rules", "warn-never-dm"],
  u6l2q1: ["warn-never-dm"],
  u6l2q2: ["warn-seed"],
  u6l2q3: ["warn-airdrop-honey"],
  u6l3t: ["warn-rug", "warn-honeypot"],
  u6l3q1: ["warn-rug"],
  u6l3q3: ["warn-honeypot"],
  u6l3q5: ["warn-urgent"],
  u6l4t: ["warn-airdrop-honey", "warn-urgent"],
  u6l4q1: ["warn-airdrop-honey"],
  u6l4q2: ["scam-drainer"],
  u6l4q3: ["warn-drained"],
  u6l4q4: ["warn-urgent"],
  u6cp1: ["warn-never-dm"],
  u6cp2: ["warn-phishing"],
  u6cp3: ["warn-rug"],
  u6cp4: ["scam-drainer"],
  u6cp5: ["warn-airdrop-honey"],
  u6cp6: ["warn-redpill"],

  u7l1q1: ["cuan-20m"],
  u7l1q2: ["rugi-paper"],
  u7l1q3: ["rugi-33m"],
  u7l2q1: ["cuan-300k"],
  u7l2q3: ["rugi-paper"],
  u7l3q1: ["fumble-193m"],
  u7l4q1: ["cuan-whale"],
  u7cp1: ["rugi-paper"],
  u7cp2: ["cuan-argus"],
  u7cp4: ["fumble-193m"],

  u8l1q1: ["rugi-liqs"],
  u8l1q2: ["rugi-33m"],
  u8l2q1: ["rugi-personal"],
  u8l2q3: ["rugi-sp500"],
  u8l3q1: ["cuan-indo-lev"],
  u8cp1: ["rugi-liqs"],
  u8cp4: ["rugi-roundtrip"],

  u9l1q1: ["rugi-nuked"],
  u9l2t: ["warn-honeypot", "warn-honeypot2"],
  u9l2q1: ["warn-honeypot"],
  u9l2q2: ["warn-honeypot2"],
  u9l2q3: ["warn-honeypot3"],
  u9l3q1: ["warn-rug"],
  u9l3q3: ["warn-honeypot4"],
  u9cp1: ["warn-honeypot"],
  u9cp3: ["warn-rug"],

  u10l2t: ["warn-approval", "warn-revoke"],
  u10l2q1: ["warn-approval"],
  u10l2q2: ["warn-revoke"],
  u10l2q3: ["warn-revoke-id"],
  u10l4q1: ["warn-never-dm"],
  u10l4q2: ["warn-phishing"],
  u10cp2: ["warn-revoke"],
  u10cp3: ["warn-never-dm"],

  u11l2q1: ["warn-urgent"],
  u11l4q1: ["warn-scam-arc"],

  u12l1q1: ["warn-urgent"],
  u12l1q2: ["warn-seed"],
  u12l3q1: ["warn-urgent"],
  u12l3q2: ["scam-drainer"],
  u12cp2: ["warn-seed"],

  u13l1q1: ["warn-urgent"],
  u13l2q1: ["rugi-personal"],
  u13l4q4: ["warn-urgent"],
  u13cp1: ["warn-urgent"],
  u13cp5: ["warn-airdrop-honey"],

  u14l2q1: ["warn-phishing"],
  u14l2q2: ["warn-drained"],
  u14l2q3: ["warn-urgent"],
  u14cp2: ["warn-never-dm"],

  u15l1q3: ["info-airdrop-sold", "drop-hype-price"],
  u15l1q4: ["drop-uni-400", "drop-uni-ath", "drop-arb-18k"],
  u15l1t: ["drop-arb-18k", "drop-wif-1k5", "drop-met-34k", "drop-uni-ath"],
  u15l1q1: ["warn-hl-phish"],
  u15l1q2: ["drop-arb-1500", "drop-arb-18k"],
  u15l1q5: ["drop-arb-18k"],
  u15l2t: ["drop-hype-dist", "drop-hl-pts", "drop-hl-tab"],
  u15l2q1: ["warn-airdrop-honey"],
  u15l2q2: ["warn-urgent"],
  u15l2q3: ["warn-drained"],
  u15l3t: ["warn-hl-phish", "drop-arb-claim"],
  u15l3q1: ["warn-hl-phish"],
  u15l4t: ["drop-met-34k", "drop-dydx-32k", "drop-top50", "drop-first-2k"],
  u15l4q1: ["drop-hype-avg"],
  u15l4q3: ["drop-jup-300", "drop-wif-1k5"],
  u15cp1: ["warn-hl-phish"],
  u15cp4: ["drop-uni-400", "drop-arb-18k"],

  u16l2q1: ["rugi-nuked"],
  u16l3q1: ["warn-rug"],
  u16l3q2: ["warn-urgent"],
  u16cp2: ["warn-rug"],

  u17l4q1: ["warn-drained"],
  u17l4q2: ["warn-redpill"],
  u17cp4: ["warn-phishing"],

  u18l1t: ["warn-hw", "warn-zach"],
  u18l1q1: ["warn-zach"],
  u18l1q2: ["warn-hw"],
  u18l1q3: ["warn-seed-rules"],
  u18l3t: ["scam-drainer", "warn-redpill"],
  u18l3q1: ["warn-redpill"],
  u18l3q2: ["scam-drainer"],
  u18l3q3: ["warn-drained"],
  u18l4q2: ["warn-sparkkitty"],
  u18l4t: ["warn-sparkkitty2", "warn-sparkkitty"],
  u18cp1: ["warn-seed-rules"],
  u18cp3: ["scam-drainer"],

  u19l2q1: ["cuan-pnut17"],
  u19l3q1: ["rugi-liqs"],
  u19l3q2: ["rugi-machi"],

  u20l2q1: ["cuan-indo-lev"],
  u20l3q1: ["warn-scam-arc"],
  u20l4q4: ["warn-urgent"],
  u20cp5: ["warn-urgent"],
};

export function proofsById(ids: string[]): Proof[] {
  return ids
    .map((id) => PROOFS.find((row) => row.id === id))
    .filter((row): row is Proof => Boolean(row));
}

export function withProofs<
  E extends { id: string; proofs?: string[] },
  L extends { exercises: E[] },
  U extends { lessons: L[] },
>(units: U[]): U[] {
  return units.map((unit) => ({
    ...unit,
    lessons: unit.lessons.map((lesson) => ({
      ...lesson,
      exercises: lesson.exercises.map((ex) => {
        if (ex.proofs && ex.proofs.length > 0) return ex;
        const clips = QUIZ_CLIPS[ex.id];
        if (!clips?.length) return ex;
        return { ...ex, proofs: clips };
      }),
    })),
  }));
}
