/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaraRouteImport } from './routes/cara'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as KisahRouteImport } from './routes/kisah'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as BedahCaseIdRouteImport } from './routes/bedah.$caseId'
import { Route as KisahIndexRouteImport } from './routes/kisah.index'
import { Route as KisahStoryIdRouteImport } from './routes/kisah.$storyId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraRoute = CaraRouteImport.update({
  id: '/cara',
  path: '/cara',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const KisahRoute = KisahRouteImport.update({
  id: '/kisah',
  path: '/kisah',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const BedahCaseIdRoute = BedahCaseIdRouteImport.update({
  id: '/bedah/$caseId',
  path: '/bedah/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const KisahIndexRoute = KisahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KisahRoute,
} as any)
const KisahStoryIdRoute = KisahStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => KisahRoute,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cara': typeof CaraRoute
  '/intro': typeof IntroRoute
  '/kisah': typeof KisahRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/bedah/$caseId': typeof BedahCaseIdRoute
  '/kisah/$storyId': typeof KisahStoryIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/kisah/': typeof KisahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cara': typeof CaraRoute
  '/intro': typeof IntroRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/bedah/$caseId': typeof BedahCaseIdRoute
  '/kisah/$storyId': typeof KisahStoryIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/kisah': typeof KisahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cara': typeof CaraRoute
  '/intro': typeof IntroRoute
  '/kisah': typeof KisahRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/bedah/$caseId': typeof BedahCaseIdRoute
  '/kisah/$storyId': typeof KisahStoryIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/kisah/': typeof KisahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cara'
    | '/intro'
    | '/kisah'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/bedah/$caseId'
    | '/kisah/$storyId'
    | '/lesson/$lessonId'
    | '/kisah/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cara'
    | '/intro'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/bedah/$caseId'
    | '/kisah/$storyId'
    | '/lesson/$lessonId'
    | '/kisah'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cara'
    | '/intro'
    | '/kisah'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/bedah/$caseId'
    | '/kisah/$storyId'
    | '/lesson/$lessonId'
    | '/kisah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaraRoute: typeof CaraRoute
  IntroRoute: typeof IntroRoute
  KisahRoute: typeof KisahRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  BedahCaseIdRoute: typeof BedahCaseIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara': {
      id: '/cara'
      path: '/cara'
      fullPath: '/cara'
      preLoaderRoute: typeof CaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisah': {
      id: '/kisah'
      path: '/kisah'
      fullPath: '/kisah'
      preLoaderRoute: typeof KisahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedah/$caseId': {
      id: '/bedah/$caseId'
      path: '/bedah/$caseId'
      fullPath: '/bedah/$caseId'
      preLoaderRoute: typeof BedahCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisah/': {
      id: '/kisah/'
      path: '/'
      fullPath: '/kisah/'
      preLoaderRoute: typeof KisahIndexRouteImport
      parentRoute: typeof KisahRoute
    }
    '/kisah/$storyId': {
      id: '/kisah/$storyId'
      path: '/$storyId'
      fullPath: '/kisah/$storyId'
      preLoaderRoute: typeof KisahStoryIdRouteImport
      parentRoute: typeof KisahRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KisahRouteChildren {
  KisahStoryIdRoute: typeof KisahStoryIdRoute
  KisahIndexRoute: typeof KisahIndexRoute
}

const KisahRouteChildren: KisahRouteChildren = {
  KisahStoryIdRoute: KisahStoryIdRoute,
  KisahIndexRoute: KisahIndexRoute,
}

const KisahRouteWithChildren = KisahRoute._addFileChildren(KisahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaraRoute: CaraRoute,
  IntroRoute: IntroRoute,
  KisahRoute: KisahRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  BedahCaseIdRoute: BedahCaseIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
